version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: run build
          command: npm run build
      - run:
          name: run lint
          command: npm run lint
      - run:
          name: run test
          command: npm run test
workflows:
  version: 2
  build_and_test:
    jobs: 
      - build